theme: jekyll-theme-slate
markdown: kramdown
title: Sterling's Floor Cleaning Robot
description: "We dream of having a clean house — but who dreams of actually doing the cleaning?" -Marcus Buckingham
